[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn scripts.main:app --host 0.0.0.0 --port $PORT"
